"""changed misspelling of freebiese

Revision ID: 67d1eb7ee0f6
Revises: 4edef77444f8
Create Date: 2023-08-05 07:56:13.310894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d1eb7ee0f6'
down_revision = '4edef77444f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freebies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('dev_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_freebies_company_id_companies')),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name=op.f('fk_freebies_dev_id_devs')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('freebnies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freebnies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('dev_id', sa.INTEGER(), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_freebnies_company_id_companies'),
    sa.ForeignKeyConstraint(['dev_id'], ['devs.id'], name='fk_freebnies_dev_id_devs'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('freebies')
    # ### end Alembic commands ###
