"""added relationshipe

Revision ID: ac3b650f0d8d
Revises: 67d1eb7ee0f6
Create Date: 2023-08-05 08:15:35.448906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3b650f0d8d'
down_revision = '67d1eb7ee0f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
